SELECT t.SCORE,
       e.EMP_NO,
       e.EMP_NAME,
       e.POSITION,
       e.EMAIL
FROM HR_EMPLOYEES e
JOIN (
    SELECT EMP_NO,
           SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
) t
ON e.EMP_NO = t.EMP_NO
WHERE t.SCORE = (
    SELECT MAX(SCORE)
    FROM (
        SELECT SUM(SCORE) AS SCORE
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO
    ) x
);